apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  labels:
    app: ap1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap1
  template:
    metadata:
      labels:
        app: ap1
    spec:
      containers:
      - name: alpine-container
        image: alpine:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-alpine
spec:
  type: NodePort
  selector:
    app: ap1
"kubalpine.yml" 39L, 585B                                                                                             1,1           Top
                                                                                                      1,1           Top
