apiVersion: apps/v1
kind: Deployment
metadata:
  name: alamap
  labels:
    app: am1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am1
  template:
    metadata:
      labels:
        app: am1
    spec:
      containers:
      - name: alma-container
        image: almalinux:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-almalinux
spec:
  type: NodePort
  selector:
    app: am1
                                                                                                                      1,1           Top
