apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: hd1
spec:
  replicas:
  selector:
    matchLabels:
      app: hd1
  template:
    metadata:
      labels:
        app: hd1
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: hd1
  ports:
"kubehttpd.yml" 37L, 539B                                                                                             1,1           Top
